### ISSUE TITLE
Add "prompt text" showing an example of a phone number

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/PhoneNumberFX#10]
If the Google lib provides it then it would be great if we could show a prompt text with an example phone number.

**Comment by gldiazcardenas** [comment]
Yes the Google lib provides "examples"..  we can use them to show a prompt text:

- com.google.i18n.phonenumbers.PhoneNumberUtil#getExampleNumber(regionCode)
- com.google.i18n.phonenumbers.PhoneNumberUtil#getExampleNumberForType(PhoneNumberType)
- com.google.i18n.phonenumbers.PhoneNumberUtil#getExampleNumberForType(regionCode,  PhoneNumberType)

I think the 1st basic method one passing the "regionCode" could be enough for this.  However, the perfect one would be the 3rd method passing the PhoneNumberType along with the regionCode, so that way the user would get better/accurate suggestion.  Maybe we can add a property so the DEVs can set the expected _phoneNumberType_?

**Comment by gldiazcardenas** [comment]
Now talking about the UI, would we use the _TextField.promptTextProperty_ to show the text?   or instead, do you want a mask that statys even when the user is typing in (similar to what I did before with the first version of this control) ?

**Comment by dlemmermann** [comment]
TextField.promptTextProperty() is the one I was referring to. No need for it to stay while the user is typing.

**Comment by gldiazcardenas** [comment]
Created PR: https://github.com/dlsc-software-consulting-gmbh/PhoneNumberFX/pull/14
